#!/bin/bash

# para_bot, the Telegram bot written in bash.
# Written by si_kabayan

#set -o nounset
#set -o errexit
#set -o pipefail

# variables --------------------------------------------------------------------

. para_bot.conf

BOT_START="$(date +%s)"
WHITELIST=no

# functions --------------------------------------------------------------------

. ./libs/bindings

# load plugins function
for file in ./plugins/*; do
  if [[ -f $file ]]; then
    . $file
  fi
done

# check if a value is in the array
contains() {
  local n=$#
  local value=${!n}
  for ((i=1;i < $#;i++)) {
    if [[ "${!i}" == "${value}" ]]; then
      printf "%s\n" "y"
      return 0
    fi
  }
  printf "%s\n" "n"
  return 1
}

skip_old_messages() {
  OFFSET="$(curl "$BASE_URL/getUpdates?timeout=30")"
  OFFSET="${OFFSET##*update_id\":}"
  OFFSET="${OFFSET%%,*}"
}

# main -------------------------------------------------------------------------

skip_old_messages

while true; do {

  get_updates

  # go to next message
  OFFSET="$((OFFSET+1))"

  if [[ $OFFSET != 1 ]]; then
    # respond to whitelisted only
    if [[ $WHITELIST = yes ]]; then
      if [[ $CHAT_ID > 0 || $(contains "${ALLOWED[@]}" "$CHAT_ID") = "y" ]]; then
        # check if message is a function
        if [[ "$(type -t $CMD)" = function ]]; then
          "$CMD"
        fi
      fi
    elif [[ $WHITELIST = no ]]; then
      if [[ "$(type -t $CMD)" = function ]]; then
        "$CMD"
      fi
    fi
  fi

} &>/dev/null; done
