#!/bin/bash

TOKEN='102512650:AAEUTgAuPp0zRoBtDzOO-RkYZLDPW2IXRF4'
URL='https://api.telegram.org/bot'$TOKEN
MSG_URL=$URL'/sendMessage?chat_id='
UPD_URL=$URL'/getUpdates?offset='
OFFSET=0
TIMEOUT='timeout=20'

function send_message {
	res=$(curl --data-urlencode "text=$2" "$MSG_URL$1&")
}

while true; do {

	res=$(curl $UPD_URL$OFFSET$TIMEOUT)

	TARGET=$(echo $res | ./libs/JSON.sh | egrep '\["result",0,"message","chat","id"\]' | cut -f 2)
	OFFSET=$(echo $res | ./libs/JSON.sh | egrep '\["result",0,"update_id"\]' | cut -f 2)
	MESSAGE=$(echo $res | ./libs/JSON.sh -s | egrep '\["result",0,"message","text"\]' | cut -f 2 | cut -d '"' -f 2)

  #TARGET=$(echo $res | jq -r '.result[0].message.chat.id')
	#OFFSET=$(echo $res | jq -r '.result[0].update_id')
	#MESSAGE=$(echo $res | jq -r '.result[0].message.text')

  MESSAGE=${MESSAGE}
  COMMAND="${MESSAGE%% *}"
  
	OFFSET=$((OFFSET+1))

  echo $res
  echo $TARGET
  echo $OFFSET
  echo $MESSAGE 
  
	if [ $OFFSET != 1 ]; then
		case $COMMAND in
			'/info')  msg="This is para_bot, the Telegram bot written in bash.";;
      '/calc')  
        msg="$(printf "%.2f\n" $(echo ${MESSAGE} | \
        sed 's|/calc ||;s|libs plugins|*|' | bc -l))"
      ;;
      '/ddg')
        QUERY="$(echo ${MESSAGE/\/ddg /} | sed 's|[!]|%21|g;s| |+|g')"
        msg="$(curl -s -X GET "https://api.duckduckgo.com/?q=%5C$QUERY&kp=1\
        &format=json&kp=1&no_redirect=1&no_html=1" | \
        sed -e 's|.*Redirect":"\(.*\)","DefinitionURL.*|\1|')";;
      '/echo')  msg="${MESSAGE/\/echo /}";;
      '/help')  
        msg="echo 'Available commands:
        - /about
        - /help [command]
        - /info
        - /calc <expression>
        - /ddg <query>
        - /echo <text>'"
      ;;
      '/kamus')  
        QUERY="${MESSAGE/\/kamus /}"
        msg="$(sed -n -e /^"$QUERY\t"/Ip ./libs/kbbi.txt | \
        sed -e "s|[\]n|\n|g;s|^$QUERY.*\t||I")"
      ;;
		esac
		send_message "$TARGET" "$msg"
	fi

} ; done
#} &>/dev/null; done
