#!/bin/bash

# para_bot, the Telegram bot written in bash.
# Written by si_kabayan
# Inspired by http://github.com/topkecleon/bashbot

# Depends on JSON.sh (http://github.com/dominictarr/JSON.sh),
# which is MIT/Apache-licensed.

# variables --------------------------------------------------------------------

TOKEN=''
URL='https://api.telegram.org/bot'$TOKEN
MSG_URL=$URL'/sendMessage?chat_id='
UPD_URL=$URL'/getUpdates?offset='
OFFSET=0
TIMEOUT='timeout=20'

# functions --------------------------------------------------------------------

function send_message {
	res=$(curl --data-urlencode "text=$2" "$MSG_URL$1&")
}

# main -------------------------------------------------------------------------

while true; do {

	res=$(curl $UPD_URL$OFFSET$TIMEOUT)

	TARGET=$(echo $res | ./libs/JSON.sh | egrep '\["result",0,"message","chat","id"\]' | cut -f 2)
	OFFSET=$(echo $res | ./libs/JSON.sh | egrep '\["result",0,"update_id"\]' | cut -f 2)
	MESSAGE=$(echo $res | ./libs/JSON.sh -s | egrep '\["result",0,"message","text"\]' | cut -f 2 | cut -d '"' -f 2)

  MESSAGE=${MESSAGE}
  COMMAND="${MESSAGE%% *}"
  
	OFFSET=$((OFFSET+1))
  
	if [ $OFFSET != 1 ]; then
		case $COMMAND in
			'/info')  msg="This is para_bot, the Telegram bot written in bash.";;
      '/calc')  
        msg="$(printf "%.2f\n" $(echo ${MESSAGE} | \
        sed 's|/calc ||;s|libs  LICENSE  para_bot  para_bot.sh  plugins  README.md|*|' | bc -l))"
      ;;
      '/ddg')
        QUERY="$(echo ${MESSAGE/\/ddg /} | sed 's|[!]|%21|g;s| |+|g')"
        msg="$(curl -s -X GET "https://api.duckduckgo.com/?q=%5C$QUERY&kp=1\
        &format=json&kp=1&no_redirect=1&no_html=1" | \
        sed -e 's|.*Redirect":"\(.*\)","DefinitionURL.*|\1|')";;
      '/echo')  msg="${MESSAGE/\/echo /}";;
      '/help')  
        msg="echo 'Available commands:
        - /about
        - /help [command]
        - /info
        - /calc <expression>
        - /ddg <query>
        - /echo <text>'"
      ;;
      '/jam') 
        H=$(date +%H)
        MS=$(date +%M:%S)
        msg=$(printf "%s\n" "UTC : $(date -u +%T)" "WIB : $H:$MS" \
        "WIT: $(($H+1)):$MS" "WITA: $(($H+2)):$MS")
      ;;
      '/kamus')  
        QUERY="${MESSAGE/\/kamus /}"
        msg="$(sed -n -e /^"$QUERY\t"/Ip ./libs/kbbi.txt | \
        sed -e "s|[\]n|\n|g;s|^$QUERY.*\t||I")"
      ;;
		esac
		send_message "$TARGET" "$msg"
	fi

} ; done
} &>/dev/null; done
